import type { Product, Category, Collection, Banner, WebsiteSettings, HomepageSettings } from '../types';

export const defaultCategories: Category[] = [
  {
    id: 'cat-rings',
    name: 'Rings',
    nameAr: 'خواتم',
    slug: 'rings',
    description: 'Beautiful rings crafted with love',
    descriptionAr: 'خواتم مميزة مصممة بشغف',
    coverImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80',
    order: 1,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-earrings',
    name: 'Earrings',
    nameAr: 'حلقان',
    slug: 'earrings',
    description: 'Charming earrings to complete your look',
    descriptionAr: 'حلقان ساحرة تكمل مظهرك',
    coverImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    order: 2,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-necklaces',
    name: 'Necklaces',
    nameAr: 'سلاسل',
    slug: 'necklaces',
    description: 'Elegant necklaces for any occasion',
    descriptionAr: 'سلاسل أنيقة لكل المناسبات',
    coverImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80',
    order: 3,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-bracelets',
    name: 'Bracelets',
    nameAr: 'أساور',
    slug: 'bracelets',
    description: 'Stylish bracelets to match your style',
    descriptionAr: 'أساور عصرية تناسب ذوقك',
    coverImage: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80',
    order: 4,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-anklets',
    name: 'Anklets',
    nameAr: 'خلخال',
    slug: 'anklets',
    description: 'Delicate anklets for a graceful touch',
    descriptionAr: 'خلخال رقيق لمسة أنيقة',
    coverImage: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=600&q=80',
    order: 5,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-pendants',
    name: 'Pendants',
    nameAr: 'انسيال',
    slug: 'pendants',
    description: 'Beautiful pendants that tell a story',
    descriptionAr: 'انسيالات جميلة تحكي قصة',
    coverImage: 'https://images.unsplash.com/photo-1617038220897-41a1f14a8ca0?auto=format&fit=crop&w=600&q=80',
    order: 6,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-sets',
    name: 'Sets',
    nameAr: 'أطقم',
    slug: 'sets',
    description: 'Coordinated jewelry sets for a complete look',
    descriptionAr: 'أطقم مجوهرات متناسقة لمظهر كامل',
    coverImage: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=600&q=80',
    order: 7,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-boutonnieres',
    name: 'Boutonnieres',
    nameAr: 'بروش بدلة',
    slug: 'boutonnieres',
    description: 'Elegant boutonnieres for special occasions',
    descriptionAr: 'بروش بدلة أنيق للمناسبات الخاصة',
    coverImage: 'https://images.unsplash.com/photo-1416041690512-f94b2ee9c0d4?auto=format&fit=crop&w=600&q=80',
    order: 8,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'cat-medals',
    name: 'Medals',
    nameAr: 'ميدليات',
    slug: 'medals',
    description: 'Statement medals and pendants',
    descriptionAr: 'ميدليات وانسيالات مميزة',
    coverImage: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=600&q=80',
    order: 9,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
];

export const defaultCollections: Collection[] = [
  {
    id: 'col-heritage',
    name: 'Heritage',
    nameAr: 'تراث',
    slug: 'heritage',
    description: 'Inspired by historical Egyptian design',
    descriptionAr: 'مستوحاة من التراث المصري العريق',
    coverImage: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    displayOrder: 1,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'col-amwaj',
    name: 'Amwaj',
    nameAr: 'أمواج',
    slug: 'amwaj',
    description: 'Flowing lines like the sea',
    descriptionAr: 'خطوط انسيابية تحاكي أمواج البحر',
    coverImage: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    displayOrder: 2,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
];

export const defaultProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Rose Gold Solitaire Ring',
    nameAr: 'خاتم سوليتير روز جولد',
    slug: 'rose-gold-solitaire-ring',
    price: 4500,
    inventory: 10,
    sku: 'TZ-RG-01',
    inStock: true,
    isFeatured: true,
    description: 'Premium handcrafted solitaire ring with a beautiful rose gold finish.',
    descriptionAr: 'خاتم سوليتير فاخر مصنوع يدوياً بطلاء روز جولد ساحر.',
    material: 'روز جولد عيار 18',
    images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80'],
    categoryId: 'cat-rings',
    collectionId: 'col-amwaj',
    tags: ['سوليتير', 'خاتم', 'روز جولد'],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'prod-2',
    name: 'Golden Heritage Necklace',
    nameAr: 'قلادة التراث الذهبية',
    slug: 'golden-heritage-necklace',
    price: 8900,
    inventory: 5,
    sku: 'TZ-HN-02',
    inStock: true,
    isFeatured: true,
    description: 'Stunning necklace inspired by ancient heritage designs.',
    descriptionAr: 'قلادة مذهلة مستوحاة من التصاميم التراثية القديمة.',
    material: 'ذهب عيار 21',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80'],
    categoryId: 'cat-necklaces',
    collectionId: 'col-heritage',
    tags: ['تراث', 'قلادة', 'ذهب'],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'prod-3',
    name: 'Natural Pearl Bracelet',
    nameAr: 'سوار اللؤلؤ الطبيعي',
    slug: 'natural-pearl-bracelet',
    price: 3200,
    inventory: 8,
    sku: 'TZ-PB-03',
    inStock: true,
    isFeatured: true,
    description: 'Handcrafted bracelet featuring genuine freshwater pearls.',
    descriptionAr: 'سوار مصنوع يدوياً يضم لآلئ مياه عذبة طبيعية.',
    material: 'لؤلؤ طبيعي وفضة 925',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80'],
    categoryId: 'cat-bracelets',
    collectionId: 'col-amwaj',
    tags: ['لؤلؤ', 'سوار', 'فضة'],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
  {
    id: 'prod-4',
    name: 'Silver Star Earrings',
    nameAr: 'أقراط النجمة الفضية',
    slug: 'silver-star-earrings',
    price: 1800,
    inventory: 15,
    sku: 'TZ-SE-04',
    inStock: true,
    isFeatured: true,
    description: 'Charming star-shaped earrings crafted in sterling silver.',
    descriptionAr: 'أقراط ساحرة على شكل نجمة مصنوعة من الفضة الإسترلينية.',
    material: 'فضة 925 مطلية بلاتين',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80'],
    categoryId: 'cat-earrings',
    collectionId: 'col-amwaj',
    tags: ['فضة', 'أقراط', 'نجمة'],
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
];

export const defaultBanners: Banner[] = [
  {
    id: 'ban-1',
    title: 'Handcrafted Egyptian Luxury',
    titleAr: 'فخامة مصرية بأيدي حرفية',
    subtitle: 'Timeless designs for modern royalty',
    subtitleAr: 'تصاميم خالدة تليق بالملوك العصرين',
    description: 'Explore our latest collections of premium gold and silver jewelry.',
    descriptionAr: 'اكتشف أحدث مجموعاتنا من المجوهرات الفاخرة المصنوعة من الذهب والفضة.',
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1800&q=80',
    buttonText: 'Shop Now',
    buttonTextAr: 'تسوق الآن',
    buttonLink: '/shop',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date() as any,
    updatedAt: new Date() as any,
  },
];

export const defaultWebsiteSettings: WebsiteSettings = {
  storeName: 'TAZGA Jewelry',
  storeNameAr: 'مجوهرات تازجا',
  tagline: 'Handcrafted Luxury Jewelry',
  taglineAr: 'مجوهرات فاخرة مصنوعة يدوياً',
  email: 'info@tazga.com',
  phone: '+20 11 12098688',
  address: 'Cairo, Egypt',
  addressAr: 'القاهرة، مصر',
  instagramUrl: 'https://instagram.com/tazga',
  facebookUrl: 'https://facebook.com/tazga',
  twitterUrl: '',
  whatsapp: '+201112098688',
  footerText: 'All rights reserved.',
  footerTextAr: 'جميع الحقوق محفوظة لعلامة تازجا.',
  logoUrl: '',
};

export const defaultHomepageSettings: HomepageSettings = {
  heroTitle: 'Artisanal Elegance',
  heroTitleAr: 'أناقة الحرفة المصرية',
  heroSubtitle: 'Handcrafted luxury jewelry telling stories of beauty',
  heroSubtitleAr: 'مجوهرات فاخرة مصنوعة يدوياً تروي قصصاً من الجمال',
  heroButtonText: 'View Collections',
  heroButtonLink: '/collections',
  aboutTitle: 'Our Heritage',
  aboutBody: 'TAZGA represents the fusion of ancient Egyptian craftsmanship and modern luxury.',
  aboutBodyAr: 'تمثل تازجا اندماج الحرفية المصرية العريقة مع الفخامة المعاصرة في عالم المجوهرات.',
  featuredSectionTitle: 'Featured Treasures',
  showTestimonials: true,
  stats: [
    { label: 'Customers', value: '10k+' },
    { label: 'Handcrafted Pieces', value: '500+' },
  ],
};
